//
//	VidyoCameraControlCapabilities_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, VCCameraControlDirection){
	VCCameraControlDirectionPanLeft,
	VCCameraControlDirectionPanRight,
	VCCameraControlDirectionTiltUp,
	VCCameraControlDirectionTiltDown,
	VCCameraControlDirectionZoomIn,
	VCCameraControlDirectionZoomOut
};
@interface VCCameraControlCapabilities : NSObject
{
}

	@property BOOL hasPhotoCapture;
	@property BOOL panTiltHasContinuousMove;
	@property BOOL panTiltHasNudge;
	@property BOOL panTiltHasRubberBand;
	@property BOOL zoomHasNudge;
	@property BOOL zoomHasRubberBand;
	@property BOOL zooomHasContinuousMove;
@end
