//
//	VidyoVirtualVideoSource_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoEndpoint_Objc.h"
#import "VidyoLocalRenderer_Objc.h"
#import "VidyoMediaFormats_Objc.h"
#import "VidyoRemoteRenderer_Objc.h"
#import "VidyoVideoFrame_Objc.h"
typedef NS_ENUM(NSInteger, VCVirtualVideoSourceType){
	VCVirtualVideoSourceTypeSHARE,
	VCVirtualVideoSourceTypeCAMERA
};
@protocol VCVirtualVideoSourceIRegisterEventListener

	-(void) startCallback:(long)frameInterval MediaFormat:(VCMediaFormat)mediaFormat UserData:(long)userData;
	-(void) reconfigureCallback:(long)frameInterval MediaFormat:(VCMediaFormat)mediaFormat UserData:(long)userData;
	-(void) stopCallback:(long)userData;
	-(void) externalMediaBufferReleaseCallback:(unsigned char*)buffer Size:(size_t)size UserData:(long)userData;
@end
@interface VCVirtualVideoSource : NSObject
{
	void* objPtr;
	@public
	id<VCVirtualVideoSourceIRegisterEventListener> virtualVideoSourceIRegisterEventListener;
}

	@property NSMutableString* id;
	@property NSMutableString* name;
	@property VCVirtualVideoSourceType type;
	-(id) init:(VCEndpoint*)endpoint Type:(VCVirtualVideoSourceType)type Id:(NSMutableString*)id Name:(NSMutableString*)name;
	-(void) dealloc;
	-(long) addToLocalRenderer:(VCLocalRenderer*)renderer;
	-(BOOL) addToRemoteRenderer:(VCRemoteRenderer*)remoteRenderer;
	-(void) clearConstraints;
	-(long) getCurrentEncodeFrameInterval;
	-(NSString*) getId;
	-(VCMediaFormat) getMediaType;
	-(NSString*) getName;
	-(NSString*) getPreviewLabel;
	-(VCVirtualVideoSourceType) getType;
	-(BOOL) isPreviewOn;
	-(BOOL) isSelected;
	-(void) onFrame:(VCVideoFrame*)videoFrame MediaFormat:(VCMediaFormat)mediaFormat;
	-(BOOL) registerEventListener:(id<VCVirtualVideoSourceIRegisterEventListener>)virtualVideoSourceIRegisterEventListener;
	-(BOOL) removeFromLocalRenderer:(VCLocalRenderer*)renderer;
	-(BOOL) removeFromRemoteRenderer:(VCRemoteRenderer*)remoteRenderer;
	-(BOOL) sendFrameWithExternalData:(VCMediaFormat)format Buffer:(unsigned char*)buffer Size:(size_t)size Width:(size_t)width Height:(size_t)height;
	-(BOOL) setBoundsConstraints:(long)maxFrameInterval MinFrameInterval:(long)minFrameInterval MaxWidth:(unsigned int)maxWidth MinWidth:(unsigned int)minWidth MaxHeight:(unsigned int)maxHeight MinHeight:(unsigned int)minHeight;
	-(BOOL) setDiscreteConstraints:(long)maxFrameInterval MinFrameInterval:(long)minFrameInterval Width:(unsigned int)width Height:(unsigned int)height;
	-(BOOL) setLowLatencyProfile:(BOOL)profile;
	-(BOOL) setMinFrameInterval:(long)frameInterval;
	-(BOOL) setPreviewLabel:(NSString*)previewLabel;
	-(BOOL) setStreamParametersInLocalRenderer:(VCLocalRenderer*)localRenderer Width:(unsigned int)width Height:(unsigned int)height FrameInterval:(long)frameInterval;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
